# Dockerfile_server
FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip && pip3 install numpy

ADD ipc_server_csv.py /server/
WORKDIR /server/
EXPOSE 9898
CMD [ "python3", "/server/ipc_server_csv.py" ]
