# Dockerfile_server
FROM ubuntu:latest
RUN apt-get update && apt-get install -y python3 python3-pip

ADD ipc_server.py /server/
WORKDIR /server/
EXPOSE 9898
CMD [ "python3", "/server/ipc_server.py" ]
